services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    # volumes:
    #   - ./api/app:/app
    entrypoint: ['npm', 'run', 'start:dev']
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://postgres:example@db:5432/sample
    depends_on:
      - db
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    tty: true
    # volumes:
    #   - ./front:/front
    entrypoint: ['npm', 'run', 'start']
    environment:
      - REACT_APP_USER_URL="http://localhost:3333/profile"
        REACT_APP_BAGS_URL="http://localhost:3333/bags"
        REACT_APP_LOGIN_URL="http://localhost:3333/auth/login"
        REACT_APP_REGISTER_URL="http://localhost:3333/register"
        REACT_APP_COUPON_URL="http://localhost:3333/coupons"
    ports:
      - 3001:3000
  ec:
    build:
      context: ./sample_ec
      dockerfile: Dockerfile
    # volumes:
    #   - ./sample_ec/app:/app
    ports:
      - 3334:3000
    environment:
      - NEXT_PUBLIC_SYSTEM_API_ROOT=http://localhost:3333
      - NEXT_PUBLIC_HOST_API_ROOT=http://localhost:3334
      - NEXT_PUBLIC_COMPANY_ID=1
    tty: true
  db:
    image: postgres:14.3
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=sample
    ports:
      - 5433:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  admin:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
